// Taygo phrases - can appear in any column
const taygoPhrases = [
  "appwrite hero",
  "mentions not being technical",
  "pepsi pat",
  "hiring jason story",
  "chat is blowing up / crazy",
  "awesome",
  "service industry being this gen's war",
  "AI mentioned",
  "torc discord",
  "i love it",
  "the stream being a virtual meetup",
  "I would put my network up against anybody's",
  "ambassador program",
  "text updates not being spam",
  "we need a part two",
  "cold brew",
  "coffee",
  "conference talk",
  "dads in tech",
  "recruiters taking 7s to read resume",
  "react js",
  ".NET",
  "laravel",
  "javascript",
  "react",
  "vue",
  "angular",
  "svelte",
  "java",
  "python",
  "ruby",
  "content creation",
  "you or your comment shouted out",
  "jason roasts taylor in chat",
  "roxy's height",
  "brand building",
  "taco bell",
  "outback steakhouse",
  "talks about sailing",
  "mentions his wife",
  "enough of me yappin",
  "set the stage",
  "hockey",
  "golf",
  "covid",
  "pre-2022 job market",
  "soft skills",
  "DM'ing people",
  "hot take",
  "grind",
  "rapid fire",
  "cursor",
  "mcp",
  "agentic",
  "claude",
  "openai",
  "vscode",
  "vim or neovim",
  "let's give the people what they want",
  "practical, tactical",
  "unnecessary hand gestures",
  "open source",
  "tech twitter",
  "interviewing sucks",
  "senior, staff, principal engineer",
  "raise or promotion",
  "rejection",
  "vaco",
  "gun.io",
  "linkedin",
  "let's dive in",
  "cut through the noise",
  "screenshare",
  "engagement",
  "south carolina",
  "nashville",
  "here's what I would do",
  "job search",
  "a bad metaphor",
  "not handy",
  "kubernetes",
];

// Jaygo phrases - can appear in any column
const jaygoPhrases = [
  "JSON head",
  "fellow kids",
  "being extra",
  "spicy take",
  "no cap",
  "that's fire",
  "low key",
  "high key",
  "it's giving",
  "main character energy",
  "touch grass",
  "sus",
  "periodt",
  "slay",
  "bet",
  "facts",
  "say less",
  "understood the assignment",
  "hits different",
  "rent free",
  "living for this",
  "not the",
  "the way I",
  "I'm deceased",
  "fam",
  "bestie",
  "chief",
  "homie",
  "bro",
  "king",
  "queen",
  "icon",
  "legend",
  "moment",
  "energy",
  "vibes",
  "mood",
  "aesthetic",
  "core",
  "era",
  "phase",
  "arc",
  "journey",
  "glow up",
  "level up",
  "upgrade",
  "rebrand",
  "pivot",
  "shift",
  "transition",
  "evolution",
  "transformation",
  "metamorphosis",
  "character development",
  "plot twist",
  "narrative",
  "storyline",
  "backstory",
  "lore",
  "canon",
  "headcanon",
  "theory",
  "conspiracy",
  "discourse",
  "drama",
  "tea",
  "spill",
  "receipts",
  "expose",
  "call out",
  "clap back",
  "ratio",
  "based",
  "cringe",
  "mid",
  "bussin",
  "sheesh",
  "valid",
  "invalid",
  "unhinged",
  "unmatched",
  "different breed",
  "built different"
];

// Function to get random phrases for a column
function generatePhraseColumn(usedPhrases = new Set()) {
  const columnPhrases = [];
  // Use the appropriate phrases array based on current theme
  const phrasesArray = currentTheme === 'jaygo' ? jaygoPhrases : taygoPhrases;
  const availablePhrases = phrasesArray.filter((phrase) => !usedPhrases.has(phrase));

  // If we don't have enough unused phrases, reset and use any
  const phrasesToUse =
    availablePhrases.length >= 5 ? availablePhrases : phrasesArray;

  while (columnPhrases.length < 5) {
    const randomIndex = Math.floor(Math.random() * phrasesToUse.length);
    const phrase = phrasesToUse[randomIndex];

    if (!columnPhrases.includes(phrase)) {
      columnPhrases.push(phrase);
      usedPhrases.add(phrase);
    }
  }

  return columnPhrases;
}
