const taygoPhrases = [
  "appwrite hero",
  "mentions not being technical",
  "pepsi pat",
  "hiring jason story",
  "chat is blowing up / crazy",
  "awesome",
  "service industry being this gen's war",
  "AI mentioned",
  "torc discord",
  "i love it",
  "the stream being a virtual meetup",
  "I would put my network up against anybody's",
  "ambassador program",
  "text updates not being spam",
  "we need a part two",
  "cold brew",
  "coffee",
  "conference talk",
  "dads in tech",
  "recruiters taking 7s to read resume",
  "react js",
  ".NET",
  "laravel",
  "javascript",
  "react",
  "vue",
  "angular",
  "svelte",
  "java",
  "python",
  "ruby",
  "content creation",
  "you or your comment shouted out",
  "jason roasts taylor in chat",
  "roxy's height",
  "brand building",
  "taco bell",
  "outback steakhouse",
  "talks about sailing",
  "mentions his wife",
  "enough of me yappin",
  "set the stage",
  "hockey",
  "golf",
  "covid",
  "pre-2022 job market",
  "soft skills",
  "DM'ing people",
  "hot take",
  "grind",
  "rapid fire",
  "cursor",
  "mcp",
  "agentic",
  "claude",
  "openai",
  "vscode",
  "vim or neovim",
  "let's give the people what they want",
  "practical, tactical",
  "unnecessary hand gestures",
  "open source",
  "tech twitter",
  "interviewing sucks",
  "senior, staff, principal engineer",
  "raise or promotion",
  "rejection",
  "vaco",
  "gun.io",
  "linkedin",
  "let's dive in",
  "cut through the noise",
  "screenshare",
  "engagement",
  "south carolina",
  "nashville",
  "here's what I would do",
  "job search",
  "a bad metaphor",
  "not handy",
  "kubernetes",
];

const jaygoPhrases = [
  "chat is blowing up / crazy",
  "awesome",
  "AI mentioned",
  "ambassador program",
  "conference talk",
  "react js",
  ".NET",
  "laravel",
  "javascript",
  "react",
  "vue",
  "angular",
  "svelte",
  "java",
  "python",
  "ruby",
  "content creation",
  "you or your comment shouted out",
  "jason roasts literally anyone",
  "roxy's height",
  "cursor",
  "mcp",
  "agentic",
  "claude",
  "openai",
  "vscode",
  "vim or neovim",
  "open source",
  "twitter",
  "interviewing sucks",
  "senior, staff, principal engineer",
  "raise or promotion",
  "rejection",
  "linkedin",
  "screenshare",
  "job search",
  "kubernetes",
  "mutes to yell at someone",
  "geez",
  "f*ck",
  "sh*t",
  "a**hole",
  "damn",
  "absolutely",
  "literally",
  "at the end of the day",
  "let's be honest",
  "to be fair",
  "mentions chip",
  "mentions jack",
  "roasts taylor",
  "roasts angelos",
  "80s reference",
  "90s reference",
  "2000s reference",
  "shows off toys",
  "discord audio issues",
  "legos",
  "talks shoes",
  "talks movies or tv",
  "talks food",
  "rodchester ny",
  "new york-ism",
  "vibe coding",
  "bolt",
  "lovable",
  "rates your resume",
  "crocs",
  "film industry",
  "forgets to put a movie on",
  "what are some wins",
  "says something is dumb",
  "drop your socials",
  "yeah",
  "buddy",
  "troll",
  "roll call",
  "whaddup",
  "forgets to wear a hat",
  "oh man",
  "I'm not a hater",
  "is being a hater",
];

// Function to get random phrases for a column
function generatePhraseColumn(usedPhrases = new Set()) {
  const columnPhrases = [];
  // Use the appropriate phrases array based on current theme
  const phrasesArray = currentTheme === 'jaygo' ? jaygoPhrases : taygoPhrases;
  const availablePhrases = phrasesArray.filter((phrase) => !usedPhrases.has(phrase));

  // If we don't have enough unused phrases, reset and use any
  const phrasesToUse =
    availablePhrases.length >= 5 ? availablePhrases : phrasesArray;

  while (columnPhrases.length < 5) {
    const randomIndex = Math.floor(Math.random() * phrasesToUse.length);
    const phrase = phrasesToUse[randomIndex];

    if (!columnPhrases.includes(phrase)) {
      columnPhrases.push(phrase);
      usedPhrases.add(phrase);
    }
  }

  return columnPhrases;
}
